Make Premake external (#25)

diff --git a/.github/workflows/premake-multi-platform.yml b/.github/workflows/premake-multi-platform.yml
--- a/.github/workflows/premake-multi-platform.yml
+++ b/.github/workflows/premake-multi-platform.yml
@@ -2,9 +2,9 @@ name: Premake on multiple platforms
 
 on:
   push:
-    branches: [ "develop" ]
+    branches: ["develop"]
   pull_request:
-    branches: [ "develop" ]
+    branches: ["develop"]
 
 jobs:
   build_windows:
@@ -13,16 +13,32 @@ jobs:
       SOLUTION_FILE_PATH: .
       BUILD_CONFIGURATION: Release
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Add MSBuild to PATH
-      uses: microsoft/setup-msbuild@v2
+      - name: Checkout FlightKit
+        uses: actions/checkout@v4
+        with:
+          repository: kietran99/FlightKitCpp
+          path: FlightKitCpp
 
-    - name: Build
-      run: |
-        .\Vendor\Binaries\Premake\Windows\premake5.exe --file=Test.lua vs2022
-        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}
+      - name: Set up Python 3.11
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
 
-    - name: Test
-      working-directory: Binaries\windows-x86_64\${{env.BUILD_CONFIGURATION}}\Test
-      run: .\Test.exe
+      - name: Add MSBuild to PATH
+        uses: microsoft/setup-msbuild@v2
+
+      - name: Build
+        run: |
+          $PremakePath = & python "FlightKitCpp\Premake\get_binaries.py"
+          if (-not $PremakePath) {
+              Write-Error "Failed to get Premake path from get_binaries.py"
+              exit 1
+          }
+          & "$PremakePath" --file=Test.lua vs2022
+          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}
+
+      - name: Test
+        working-directory: Binaries\windows-x86_64\${{env.BUILD_CONFIGURATION}}\Test
+        run: .\Test.exe
